application:
  generate:
    # 驱动类
    driver-class: com.mysql.cj.jdbc.Driver
    # 用户名
    username: root
    # 密码
    password: root
    # 库名
    catalog: generate
    # 数据库地址
    url: jdbc:mysql://127.0.0.1:3306/generate?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    # 主键名称
    id: id
