application:
  generate:
    # 驱动类
    driver-class: com.mysql.cj.jdbc.Driver
    # 用户名
    username: root
    # 密码
    password: 521piiig
    # 库名
    catalog: ddd
    # 数据库地址
    url: jdbc:mysql://127.0.0.1:3306/ddd?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
